development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: biomart_development
  pool: 5
  username: root
  password: deddy97
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: biomart_test
  pool: 5
  username: root
  password: deddy97
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: biomart_production
  pool: 5
  username: root
  password: deddy97
  socket: /tmp/mysql.sock
